# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Calcifer
email: andry.tino@hotmail.com
description: A tutorial for creating your first cross-platform app with Cordova tools in Microsoft Visual Studio 2015
baseurl: "/t-calcifer" # the subpath of your site, e.g. /blog
url: "http://andry-tino.github.io" # the base hostname & protocol for your site

author_url: "https://github.com/andry-tino"
author: Andrea Tino

repo_name: t-calcifer
repo_url: "https://github.com/andry-tino/t-calcifer"
repo_zip_url: "https://github.com/andry-tino/t-calcifer/zipball/master"
repo_tar_url: "https://github.com/andry-tino/t-calcifer/tarball/master"
repo_fork_url: "https://github.com/andry-tino/t-calcifer"

twitter_username: _atino
github_username:  andry-tino

theme_forked_url: "https://github.com/andry-tino/minimal"
theme_forked: "orderedlist/minimal"

socialmedia_url: "https://github.com/darklow/social-share-kit"
socialmedia: "Social Share Kit"

# Build settings
markdown: kramdown
